//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangSanXuat
    {
        public int ID { get; set; }
        public string TenHangSX { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public Nullable<bool> KichHoat { get; set; }
    }
}
