//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalEntities : DbContext
    {
        public HospitalEntities()
            : base("name=HospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietPhanQuyen> ChiTietPhanQuyens { get; set; }
        public virtual DbSet<ChucNangQuanLy> ChucNangQuanLies { get; set; }
        public virtual DbSet<DonViTinh> DonViTinhs { get; set; }
        public virtual DbSet<LichSuGia> LichSuGias { get; set; }
        public virtual DbSet<NCC_KH> NCC_KH { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhomThuoc> NhomThuocs { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<PhieuNhapThuoc> PhieuNhapThuocs { get; set; }
        public virtual DbSet<Thuoc> Thuocs { get; set; }
        public virtual DbSet<CT_Thuoc_PhieuNhap> CT_Thuoc_PhieuNhap { get; set; }
        public virtual DbSet<CT_Thuoc_PhieuXuat> CT_Thuoc_PhieuXuat { get; set; }
        public virtual DbSet<HangSanXuat> HangSanXuats { get; set; }
        public virtual DbSet<HoatChat> HoatChats { get; set; }
        public virtual DbSet<LoaiDonThuoc> LoaiDonThuocs { get; set; }
        public virtual DbSet<NuocSanXuat> NuocSanXuats { get; set; }
        public virtual DbSet<TrangThaiPhieu> TrangThaiPhieux { get; set; }
        public virtual DbSet<PhieuXuatThuoc> PhieuXuatThuoc { get; set; }
        public virtual DbSet<Kho> Kho { get; set; }
    }
}
