//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapThuoc
    {
        public long ID { get; set; }
        public Nullable<int> NCC_KH_ID { get; set; }
        public string SoPhieu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<double> ThueSuat { get; set; }
        public string SoSeri { get; set; }
        public string SoHoaDon { get; set; }
        public Nullable<System.DateTime> NgayHoaDon { get; set; }
        public Nullable<double> TongTienTruocThue { get; set; }
        public Nullable<double> ChietKhau { get; set; }
        public Nullable<double> TongTienTra { get; set; }
    }
}
