//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV_DEV
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DonViTinh
    {
        public long ID { get; set; }
        public Nullable<long> Thuoc_ID { get; set; }
        public Nullable<int> DVT_ID { get; set; }
        public Nullable<long> QuyDoi { get; set; }
        public Nullable<bool> KichHoat { get; set; }
        public string TenDVT { get; set; }
    }
}
