using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using QLBV_DEV.Repository;

using System.Data.Entity.Validation;
using System.Diagnostics;

using DevExpress.XtraGrid.Views.Grid;


namespace QLBV_DEV
{
    public partial class frmNhomThuoc : DevExpress.XtraEditors.XtraForm
    {
        #region params
        int NhomThuoc_Id = 0;
        NhomThuocRepository repository = new NhomThuocRepository();
        HospitalEntities db = new HospitalEntities();
        bool isUpdate = false;
        #endregion

        public frmNhomThuoc()
        {
            InitializeComponent();
            LoadDS_NhomThuoc();
        }
        
        private void btnThem_Click(object sender, EventArgs e)
        {
            //frmThemNuocSanXuat frmThemNuocSanXuat = new frmThemNuocSanXuat();
            //frmThemNuocSanXuat.ShowInTaskbar = false;
            //frmThemNuocSanXuat.FormClosed += new FormClosedEventHandler(close_form);
            //frmThemNuocSanXuat.ShowDialog();
        }
        private void LoadDS_NhomThuoc()
        {
            try
            {
                QLBV_DEV.HospitalEntities dbContext = new QLBV_DEV.HospitalEntities();
                // Call the Load method to get the data for the given DbSet from the database.
                dbContext.NhomThuoc.Load();
                // This line of code is generated by Data Source Configuration Wizard
                gridcontrolNhomThuoc.DataSource = dbContext.NhomThuoc.Local.ToBindingList();
            }
            catch (Exception)
            {
                MessageBox.Show(QLBV_DEV.Helpers.ErrorMessages.show(1));
            }
        }
        private void close_form(object sender, FormClosedEventArgs e)
        {
            LoadDS_NhomThuoc();
        }

        private void btnXoa_Click(object sender, EventArgs e)
        {
            try
            {
                if (NhomThuoc_Id > 0)
                {
                    String ten = grvNhomThuoc.GetRowCellValue(grvNhomThuoc.FocusedRowHandle, "TenNhom").ToString();
                    DialogResult dialogResult = MessageBox.Show(ten, "Xác nhận xóa?", MessageBoxButtons.YesNo);
                    if (dialogResult == DialogResult.Yes)
                    {
                        repository.Delete(NhomThuoc_Id);


                        // Tải lại danh sách nước sản xuất
                        LoadDS_NhomThuoc();
                    }
                    else if (dialogResult == DialogResult.No)
                    {
                        //do something else
                    }                               
                }
            }
            catch (Exception)
            {
                MessageBox.Show(QLBV_DEV.Helpers.ErrorMessages.show(1));
            }
        }


        private void btnLuu_Click(object sender, EventArgs e)
        {
            #region Code Save cũ
            //if (dxValidate.Validate())
            //{
            //    NuocSanXuat _object = new NuocSanXuat()
            //    {
            //        TenNuoc = txtTenNuoc.Text.Trim()
            //    };

            //    try
            //    {
            //        if (isUpdate && nuocsanxuat_Id > 0)
            //        {
            //            NuocSanXuat objNuocSanXuat = db.NuocSanXuat.Where(p => p.ID == nuocsanxuat_Id).SingleOrDefault();
            //            objNuocSanXuat.TenNuoc = txtTenNuoc.Text.Trim();

            //            db.SaveChanges();
            //            // Tải lại danh sách nước sản xuất

            //        }
            //        else
            //        {
            //            repository.Create(_object);

            //            txtTenNuoc.Text = "";
            //            MessageBox.Show("Lưu thành công");
            //        }
            //        LoadDS_NuocSanXuat();

            //    }
            //    catch (DbEntityValidationException dbEx)
            //    {
            //        foreach (var validationErrors in dbEx.EntityValidationErrors)
            //        {
            //            foreach (var validationError in validationErrors.ValidationErrors)
            //            {
            //                Trace.TraceInformation(
            //                      "Class: {0}, Property: {1}, Error: {2}",
            //                      validationErrors.Entry.Entity.GetType().FullName,
            //                      validationError.PropertyName,
            //                      validationError.ErrorMessage);
            //            }
            //        }
            //    }
            //}
            //else
            //{
            //    MessageBox.Show("Lỗi");
            //}
            #endregion

            NhomThuoc obj_NhomThuoc;
            try
            {
                if (isUpdate && NhomThuoc_Id > 0)
                {
                    obj_NhomThuoc = db.NhomThuoc.Where(p => p.ID == NhomThuoc_Id).SingleOrDefault();
                }
                else
                {
                    obj_NhomThuoc = new NhomThuoc();
                }
                obj_NhomThuoc.TenNhom = txtTenNhom.Text.Trim();

                if (isUpdate && NhomThuoc_Id > 0) // Cập nhật
                {
                    //respository.Save(objNuocSanXuat);
                    db.SaveChanges();

                }
                else // Thêm mới
                {
                    repository.Create(obj_NhomThuoc);
                    //db.NCC_KH.Add(_object);
                    //db.SaveChanges(); 
                    txtTenNhom.Text = "";
                }
                LoadDS_NhomThuoc();
            }
            catch (Exception)
            {
                MessageBox.Show(QLBV_DEV.Helpers.ErrorMessages.show(1));
            }
            //catch (DbEntityValidationException dbEx)
            //{
            //    foreach (var validationErrors in dbEx.EntityValidationErrors)
            //    {
            //        foreach (var validationError in validationErrors.ValidationErrors)
            //        {
            //            Trace.TraceInformation(
            //                  "Class: {0}, Property: {1}, Error: {2}",
            //                  validationErrors.Entry.Entity.GetType().FullName,
            //                  validationError.PropertyName,
            //                  validationError.ErrorMessage);
            //        }
            //    }
            //}
            
        }

        private void gridcontrolNhomThuoc_Click(object sender, EventArgs e)
        {
            // dừng xử lý nếu không kích vào dòng có dữ liệu
            if (grvNhomThuoc.GetRowCellValue(grvNhomThuoc.FocusedRowHandle, "ID") == null)
                return;

            string id = grvNhomThuoc.GetRowCellValue(grvNhomThuoc.FocusedRowHandle, "ID").ToString();
            NhomThuoc_Id = Convert.ToInt32(id);
            isUpdate = true;
            //MessageBox.Show(id); 
            txtTenNhom.Text = grvNhomThuoc.GetRowCellValue(grvNhomThuoc.FocusedRowHandle, "TenNhom").ToString();
        }

        // Thêm số thứ tự tự động tăng GridControl
        //bool indicatorIcon = true;
        private void grvNuocSanXuat_CustomDrawRowIndicator(object sender, DevExpress.XtraGrid.Views.Grid.RowIndicatorCustomDrawEventArgs e)
        {
             GridView view = (GridView)sender;
            if (e.Info.IsRowIndicator && e.RowHandle >=0)
            {
                e.Info.DisplayText = (e.RowHandle+1).ToString();
                //if (!indicatorIcon)
                   // e.Info.ImageIndex = -1;
            }

        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {

        }

        private void btnSua_Click(object sender, EventArgs e)
        {
            if (NhomThuoc_Id > 0)
            {
                layoutControlGroup2.Expanded = true;
                txtTenNhom.Focus();

            }
            else
            {
                MessageBox.Show("Hãy lựa chọn dòng cần sửa.");
            }
        }

        private void btnThem_Click_1(object sender, EventArgs e)
        {
            layoutControlGroup2.Expanded = true;
            txtTenNhom.Focus();
            txtTenNhom.Text = "";
            isUpdate = false;
        }

        private void frmNhomThuoc_Load(object sender, EventArgs e)
        {

        }
    }
}