//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV_DEV
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuCapNhatGia
    {
        public long ID { get; set; }
        public Nullable<long> Thuoc_ID { get; set; }
        public Nullable<double> GiaBanLeCu { get; set; }
        public Nullable<double> GiaBanLeMoi { get; set; }
        public Nullable<double> GiaBanBuonCu { get; set; }
        public Nullable<double> GiaBanBuonMoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> UserTao { get; set; }
    }
}
