//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV_DEV
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuGia
    {
        public int ID { get; set; }
        public Nullable<int> ThuocID { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<double> GiaBanCu { get; set; }
        public Nullable<double> GiaBanMoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    }
}
