//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV_DEV
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDieuChinh
    {
        public long ID { get; set; }
        public string MaPhieuDieuChinh { get; set; }
        public string TenPhieuDieuChinh { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> UserTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> Huy { get; set; }
        public Nullable<int> UserHuy { get; set; }
    }
}
