//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV_DEV
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuatThuoc
    {
        public long ID { get; set; }
        public Nullable<int> NCC_KH_ID { get; set; }
        public Nullable<int> TrangThaiPhieu_ID { get; set; }
        public Nullable<int> LoaiHinhBan_ID { get; set; }
        public string SoPhieu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<double> ThueSuat { get; set; }
        public string SoSeri { get; set; }
        public string SoHoaDon { get; set; }
        public Nullable<System.DateTime> NgayHoaDon { get; set; }
        public Nullable<double> TongTienTruocThue { get; set; }
        public Nullable<double> ChietKhau { get; set; }
        public Nullable<double> TongTienKHTra { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public Nullable<int> UserXoa { get; set; }
        public Nullable<int> UserTao { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
    }
}
