//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV_DEV
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinChung
    {
        public int ID { get; set; }
        public string Ten { get; set; }
        public string HinhAnh { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string MST { get; set; }
        public string Website { get; set; }
        public Nullable<bool> KichHoat { get; set; }
        public string TaiKhoan { get; set; }
        public string NganHang { get; set; }
        public string NguoiPhuTrach { get; set; }
    }
}
