//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBV_DEV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thuoc
    {
        public long ID { get; set; }
        public Nullable<int> NhomThuoc_ID { get; set; }
        public Nullable<int> HangSanXuat_ID { get; set; }
        public Nullable<int> HoatChat_ID { get; set; }
        public Nullable<int> DVT_Nguyen_ID { get; set; }
        public Nullable<int> DVT_Le_ID { get; set; }
        public string Barcode { get; set; }
        public string MaThuoc { get; set; }
        public string TenThuoc { get; set; }
        public Nullable<double> GiaBanLe { get; set; }
        public Nullable<double> GiaBanBuon { get; set; }
        public Nullable<double> QuyCach { get; set; }
        public Nullable<int> TonKho { get; set; }
        public Nullable<System.DateTime> ThoiGianCanhBaoHetHan { get; set; }
        public Nullable<int> TonKhoToiThieu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> KichHoat { get; set; }
    }
}
