//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachNhapHang
    {
        public long ID { get; set; }
        public Nullable<int> HangSanXuatID { get; set; }
        public Nullable<int> NuocSanXuatID { get; set; }
        public Nullable<long> PhieuNhapHangID { get; set; }
        public Nullable<long> ThuocID { get; set; }
        public Nullable<int> ViTriID { get; set; }
        public Nullable<int> KhoID { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<System.DateTime> HanSuDung { get; set; }
        public Nullable<int> TongSoDaBan { get; set; }
    }
}
