//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonThuoc
    {
        public long ID { get; set; }
        public Nullable<int> BacSyID { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<bool> ChoCapThuoc { get; set; }
        public string KhachHang { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public string SDT { get; set; }
        public string SoDH { get; set; }
        public string DiaChi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<double> TienThuoc { get; set; }
        public Nullable<double> PhuPhi { get; set; }
        public Nullable<double> KhachHangTra { get; set; }
    }
}
