//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public int ID { get; set; }
        public string MaNCC { get; set; }
        public string TenNCC { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> TinhTPID { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string MST { get; set; }
        public string SoTaiKhoan { get; set; }
        public string NganHang { get; set; }
        public string MoTai { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string MoTa { get; set; }
        public Nullable<bool> KichHoat { get; set; }
    }
}
