//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public long ID { get; set; }
        public int KhoaID { get; set; }
        public int PhanQuyenID { get; set; }
        public string HoVaTen { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public bool GioiTinh { get; set; }
        public DateTime NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string CMT { get; set; }
        public bool KichHoat { get; set; }
    }
}
