//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapHang
    {
        public long ID { get; set; }
        public Nullable<int> NhaCCID { get; set; }
        public Nullable<long> DonThuocID { get; set; }
        public string DiaChi { get; set; }
        public string GhiChu { get; set; }
        public string SoPhieu { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<double> ThueSuat { get; set; }
        public string SoSeri { get; set; }
        public string SoHD { get; set; }
        public Nullable<System.DateTime> NgayHD { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string SoDH { get; set; }
    }
}
