//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thuoc
    {
        public long ID { get; set; }
        public string MaThuoc { get; set; }
        public string BarCode { get; set; }
        public string TenThuoc { get; set; }
        public Nullable<int> NhomThuocID { get; set; }
        public Nullable<double> GiaBanLe { get; set; }
        public Nullable<double> GiaBanBuon { get; set; }
        public Nullable<int> DonViTinh { get; set; }
        public Nullable<int> DonViTinhQuyDoi { get; set; }
        public string QuyCach { get; set; }
    }
}
